CREATE SEQUENCE bm_id_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE bookmarker (
    id BIGINT DEFAULT NEXTVAL('bm_id_seq') NOT NULL PRIMARY KEY,
    link VARCHAR(255),
    name VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);
